name: cs608_p2
channels:
  - defaults
dependencies:
  - python=3.11.9
  - pip=24.0.0
  - pip:
    - cornac==2.2.1
    - matplotlib==3.8.4
    - numpy==1.24.3
    - pandas==2.2.1
    - pillow==10.3.0
    - scipy==1.13.1
    - seaborn==0.12.2
    - torch==2.3.0
    - torchaudio==2.3.0
    - torchvision==0.18.0
    - tqdm==4.66.4
    - wheel==0.43.0
    - kaggle==1.6.14
    - scrapy==2.11.1
